### ISSUE TITLE
Is this package released in pypi?

### ISSUE THREAD

**Issue by ghost** [AustEcon/bsvbip32#1]
I can't find this package in pypi.
Is this package released in pypi?

**Comment by ghost** [comment]
@AustEcon Sorry, I forgot add a mention.

**Comment by AustEcon** [comment]
No it's not I'm afraid... I would be a bit embarrassed to put this on pypi in its current form...
I basically planned on migrating the dependencies to be entirely based on bitcoinX because that's what I want all of my other stuff to interoperate with...

So if you want to help out that would be part of the general roadmap.

The next thing would be instances of bitsv PrivateKey classes at the 'leaves' of the bip32 derivation tree...

**Comment by ghost** [comment]
Thank you for your reply.
When I want to use function of bsvbip32, may I add function to bitsv(PrivateKey class in bitsv)? (I add pull request for you)
For example, I need wif method of Bip32 class in bsvbip32.

**Comment by AustEcon** [comment]
I'm not exactly sure what you mean. But the general plan was to not change bitsv too much (PrivateKey class can already do key conversions to/from various formats) but have bsvbip32 as a higher layer of abstraction to provide bitsv functionality for any derived key. I haven't had much time though so not sure when I'll get to do any of this stuff... so don't let me be a bottleneck for you...

**Comment by ghost** [comment]
@AustEcon 
Sorry, I see. I just want to use bsvbip32 features.
But I found other way.
You got my respect. Thank you for taking the time out to help me.
I will close this issue.
